version: '3.8'
services:
  backend:
    image: b-image:latest
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=mysql://root:root@db/esd_database
    depends_on:
      db:
        condition: service_healthy

  frontend:
    image: f-image:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: esd_database
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

volumes:
  mysql-data:
